export const ingredientsExemple = [
  'abricot',
  'ail',
  'ail',
  'amande',
  'ananas',
  'aneth',
  'artichaut',
  'aubergine',
  'avocat',
  'avoine',
  'bacon',
  'baguette',
  'banane',
  'bar',
  'basilic',
  'beurre',
  'bicarbonate',
  'blancs',
  'bleu',
  'blé',
  'boeuf',
  'bouillon',
  'brie',
  'brocoli',
  'cabillaud',
  'cacahuète',
  'cacao',
  'camembert',
  'canneberges',
  'cannelle',
  'cantal',
  'cardamome',
  'carotte',
  'cassis',
  'cassonade',
  'cerise',
  'champignon',
  'chapelure',
  'charcuterie',
  'chocolat',
  'chorizo',
  'chou-fleur',
  'châtaigne',
  'chèvre',
  'ciboulette',
  'citron',
  'clou de girofle',
  'clou',
  'comté',
  'concombre',
  'courgette',
  'crabe',
  'crevettes',
  'croissant',
  'crème fraîche',
  'crème',
  'cumin',
  'curcuma',
  'câpres',
  'céleris',
  'eau',
  'emmental',
  'extrait',
  'farine',
  'feta',
  'figue',
  'flocons',
  'fraise',
  'fraises',
  'framboise',
  'fromage',
  'fructose',
  'fruit de la passion',
  'fève',
  'fécule',
  'gingembre',
  'graine de chia',
  'graine de courge',
  'graine de lin',
  'graine de pavot',
  'graine de sésame',
  'graine de tournesol',
  'gruyère',
  'haricot',
  'homard',
  'huile d\'olive',
  'huile',
  'huîtres',
  'jambon',
  'jaunes',
  'jus',
  'kiwi',
  'lait',
  'langoustines',
  'lardon',
  'laurier',
  'lentille',
  'limes',
  'mandarine',
  'mayonnaise',
  'maïs',
  'melon',
  'menthe',
  'merlu',
  'miel',
  'moules',
  'moutarde',
  'mozzarella',
  'muscade',
  'myrtille',
  'mûre',
  'noisette',
  'noix de cajou',
  'noix de coco',
  'noix de muscade',
  'noix',
  'oeuf',
  'oignon',
  'orange',
  'orge',
  'origan',
  'origan',
  'ossau-iraty',
  'pacanes',
  'pain aux céréales',
  'pain aux noix',
  'pain aux raisins',
  'pain complet',
  'pain de mie',
  'pain de seigle',
  'pain sans gluten',
  'pain',
  'pamplemousse',
  'paprika',
  'parmesan',
  'pastèque',
  'persil',
  'petit pois',
  'pistache',
  'poire',
  'poireaux',
  'pois chiche',
  'poisson',
  'poitrine',
  'poivre',
  'poivron',
  'pomme de terre',
  'pomme',
  'porc',
  'poudre',
  'poulet',
  'prune',
  'pâte brisée',
  'pâte feuilletée',
  'pâte à pain',
  'pâte à pizza',
  'pâte à tarte',
  'pâte',
  'pêche',
  'quinoa',
  'raclette',
  'radis',
  'raisin',
  'rhubarbe',
  'ricotta',
  'riz',
  'romarin',
  'roquefort',
  'roquette',
  'salade',
  'sambal',
  'sardine',
  'sauce soja',
  'sauce',
  'saucisse',
  'saucisson',
  'sauge',
  'saumon',
  'sel',
  'semoule',
  'sirop d\'agave',
  'sirop d\'hibiscus',
  'sirop d\'orge',
  'sirop d\'érable',
  'sirop de baobab',
  'sirop de bergamote',
  'sirop de betterave',
  'sirop de blé',
  'sirop de camomille',
  'sirop de canne à sucre',
  'sirop de cannelle',
  'sirop de caroube',
  'sirop de citronnelle',
  'sirop de coco',
  'sirop de cédrat',
  'sirop de dattes',
  'sirop de figues',
  'sirop de fleurs',
  'sirop de glucose',
  'sirop de jasmin',
  'sirop de laurier',
  'sirop de lavande',
  'sirop de malt',
  'sirop de malt',
  'sirop de maltose',
  'sirop de manioc',
  'sirop de maïs',
  'sirop de menthe',
  'sirop de pomme de terre',
  'sirop de raisins',
  'sirop de riz blanc',
  'sirop de riz brun',
  'sirop de riz',
  'sirop de rose',
  'sirop de réglisse',
  'sirop de sarrasin',
  'sirop de sorgho',
  'sirop de sureau',
  'sirop de sève de palmier',
  'sirop de tapioca',
  'sirop de thé blanc',
  'sirop de thé noir',
  'sirop de thé vert',
  'sirop de tilleul',
  'sirop de verveine',
  'sirop',
  'stévia',
  'sucre d\'érable',
  'sucre de bouleau',
  'sucre de canne',
  'sucre de coco',
  'sucre glace',
  'sucre roux',
  'sucre vanillé',
  'sucre',
  'thon',
  'thym',
  'tomate',
  'truite',
  'vanille',
  'viande d\'agneau',
  'viande de bœuf',
  'viande de canard',
  'viande de dinde',
  'viande de gibier',
  'viande de lapin',
  'viande de porc',
  'viande de poulet',
  'viande de veau',
  'vin',
  'vinaigre balsamique',
  'vinaigre de cidre',
  'vinaigre de vin',
  'vinaigre',
  'xylitol',
  'yaourt',
  'zeste',
  'échalotes',
  'épinard',
];
